# Copyright 2009 laliputienses
# License: GPL v3
# For further info, see LICENSE file

CONNECTION_MADE = 0
CONNECTION_LOST = 1
SIGNED_ON = 2
JOINED = 3
PRIVATE_MESSAGE = 4
TALKED_TO_ME = 5
PUBLIC_MESSAGE = 6
COMMAND = 7
ACTION = 8
JOIN = 9
LEFT = 10
QUIT = 11
KICK = 12
RENAME = 13
